services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-9000}:9000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network
